# Generated by Django 3.2.12 on 2023-03-22 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_added',
            field=models.DateField(auto_created=datetime.date(2023, 3, 22), blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_created=datetime.date(2023, 3, 22), blank=True)),
                ('first_name', models.CharField(blank=True, max_length=100000)),
                ('last_name', models.CharField(blank=True, max_length=100000)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('portfolio', models.URLField(blank=True)),
                ('resume', models.FileField(upload_to='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job')),
            ],
        ),
    ]
