# Generated by Django 3.2.12 on 2023-03-24 17:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230322_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='apply',
            name='date_added',
            field=models.DateField(auto_created=datetime.date(2023, 3, 24), blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_added',
            field=models.DateField(auto_created=datetime.date(2023, 3, 24), blank=True),
        ),
        migrations.CreateModel(
            name='Course_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=10000)),
                ('video', models.FileField(blank=True, upload_to='')),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
    ]
