# Generated by Django 3.2.12 on 2023-03-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230324_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
