# Generated by Django 3.2.12 on 2023-03-25 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_course_topic_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='date_added',
            field=models.DateField(auto_created=datetime.date(2023, 3, 25), blank=True),
        ),
        migrations.AlterField(
            model_name='course_topic',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_added',
            field=models.DateField(auto_created=datetime.date(2023, 3, 25), blank=True),
        ),
    ]
