# Generated by Django 3.2.12 on 2023-03-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230325_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_topic',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
